### PR TITLE
stop timeouting after 45 seconds [ready for review]

### LINKED ISSUE #1010: integration tests are prone to failing with java.net.SocketTimeoutException
It applies to both add_housenumber and construction group of integration tests.

This tests sometimes fail with `de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.SocketTimeoutException: failed to connect to overpass-api.de/178.63.11.215 (port 443) after 45000ms: isConnected failed: ETIMEDOUT (Connection timed out)`

It is happening despite overpass turbo operating without any issues.

It was happening also before I started making any changes to integration tests and from what I experienced starting to use attic data failed to change frequency of this issue.

Failures are intermittent, typically disappearing once I decide to debug this issue :)

I think that implementing https://github.com/westnordost/osmapi/issues/16 would be a good first step toward figuring what is causing this problem - can you confirm that it would be a viable PR?

### PR DESCRIPTION
**Pull request by matkoniecz**
default overpass timeout is 180 seconds
should fix #1010, may help with #1466

Construction tests started failing in a new way, but quest download already works nicer

> AddBusStopName: Added 0 new and removed 0 already resolved quests. (Total: 0) in 82s

> AddPlaceName: Added 41 new and removed 0 already resolved quests. (Total: 41) in 95s

logged in my testing would be a timeout errors before this change (BTW, I wonder is AddBusStopName unreasonably expensive or is it just an unlucky call)

### CODE REVIEW

**Comment by rugk** [comment]
If it fixes #1010 maybe we can re-enable integration tests for CI? (AFAIK they were disabled, because of that issue.)

**Comment by matkoniecz** [comment]
Nope. See log of CI tests, startup of emulator was failing.

File: app/src/main/java/de/westnordost/streetcomplete/data/OsmModule.java [hunk 1]
```diff
@@ -64,19 +64,29 @@ public static OsmConnection osmConnection(OAuthConsumer consumer)
...
 	}
 
+	public static int defaultOverpassTimeoutInMiliseconds(){
+		// see https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#timeout:
+		// default value is 180 seconds
+		// give additional 4 seconds to get and process refusal from Overpass
+		// or maybe a bit late response rather than trigger timeout exception
+		return (180 + 4) * 1000;
+	}
+
```
Comment (westnordost) [inline app/src/main/java/de/westnordost/streetcomplete/data/OsmModule.java]: `private static int DEFAULT_OVERPASS_TIMEOUT_IN_SECONDS`?
The link to the Overpass Api documentation  note about the 4 seconds is probably enough here

**Comment by westnordost** [comment]
AddBusStopName is quite expensive, because of the `or`s.

**Comment by westnordost** [comment]
@PR: Makes sense, if the default Overpass timeout is that long!

File: app/src/main/java/de/westnordost/streetcomplete/data/OsmModule.java (hunk 1 above)
Comment (matkoniecz) [reply app/src/main/java/de/westnordost/streetcomplete/data/OsmModule.java]: I moved to `OVERPASS_QUERY_TIMEOUT_IN_MILISECONDS` name as 184 seconds (including extra buffer) is not actually equal to overpass timeout. 

I used miliseconds to avoid later `* 1000`.

Hopefully it is OK.
