### PR TITLE
fixed form compleate after selecting road name

### LINKED ISSUE #6630: What's the name of this road? - unexpected behaviour off app.
When answering the quest "What's the name of this road?" If i tap an already named road to apply the name to the selected way, the "tick box" for applying the answer doesn't appear until I edit the text. (personal opinion, i preferred the drop down menu, which is now gone) 

While this doesn't add to much time to editing, it is strange behaviour to select the correct name from another road, but still have to edit the text to confirm it.

I would have thought that text populating the box, would make the tick appear, and makes confirming quite "clunky"

Street Complete app version is V62.0
Android version is Android 12, on Samsung One UI version 4.1 (galaxy S10e)

I have also tried this on a second android device (galaxy Zflip5), with the same results

I have a YouTube Video link of the "issue": https://youtube.com/shorts/kFFkBjSFIAE?feature=share

p.s. please bring back the drop down box, it was my love 🥺, and i had hoped it would get expanded to things like adding a road to a building address

### PR DESCRIPTION
**Pull request by paulklie**
fixes #6630

### CODE REVIEW

File: app/src/androidMain/kotlin/de/westnordost/streetcomplete/quests/road_name/AddRoadNameForm.kt [hunk 1]
```diff
@@ -31,6 +31,7 @@ class AddRoadNameForm : AAddLocalizedNameForm<RoadNameAnswer>() {
             .firstOrNull()
             ?.let { localizedNames.value = it }
 
+        checkIsFormComplete()
```
Comment (westnordost) [inline app/src/androidMain/kotlin/de/westnordost/streetcomplete/quests/road_name/AddRoadNameForm.kt]:
```suggestion
            ?.let {
                localizedNames.value = it
                checkIsFormComplete()
            }
```

The completeness only needs to be changed when localizedNAmes is set, not on every map click.

**Comment by westnordost** [comment]
I didn't test my suggestion, I just wrote it in the browser, did you?

**Comment by paulklie** [comment]
> I didn't test my suggestion, I just wrote it in the browser, did you?

yep! worked

**Comment by westnordost** [comment]
Thanks!
